# `개폐업률 정리하기`

In [2]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
import PublicDataReader as pdr

In [3]:
a = pd.read_csv("./임시/신생기업생존률.csv", encoding = "ansi", header = 1)

In [14]:
a.shape

(261, 14)

In [4]:
a.columns

Index(['행정구역', '생활밀접업종', '1년 생존율', '3년 생존율', '5년 생존율', '1년 생존율.1', '3년 생존율.1',
       '5년 생존율.1', '1년 생존율.2', '3년 생존율.2', '5년 생존율.2'],
      dtype='object')

In [6]:
b = pd.concat([a.iloc[:,[0,1]],a.iloc[:,-3:]], axis = 1)
b

,행정구역,생활밀접업종,1년 생존율.2,3년 생존율.2,5년 생존율.2
0,행정구역,Unnamed: 1_level_2,Unnamed: 8_level_2,Unnamed: 9_level_2,Unnamed: 10_level_2
1,하위 메뉴 펼침서울시 전체,외식업/ 전체,76.1,50.9,33.6
2,하위 메뉴 펼침종로구,외식업/ 전체,80.5,57.3,39.3
3,하위 메뉴 펼침중구,외식업/ 전체,81.3,56.0,36.2
4,하위 메뉴 펼침용산구,외식업/ 전체,84.6,55.7,38.3
5,하위 메뉴 펼침성동구,외식업/ 전체,82.6,53.0,35.5
6,하위 메뉴 펼침광진구,외식업/ 전체,76.2,52.7,32.8
7,하위 메뉴 펼침동대문구,외식업/ 전체,76.4,51.5,34.3
8,하위 메뉴 펼침중랑구,외식업/ 전체,74.4,45.6,30.4
9,하위 메뉴 펼침성북구,외식업/ 전체,79.1,57.9,34.6
10,하위 메뉴 펼침강북구,외식업/ 전체,73.4,48.2,31.7
11,하위 메뉴 펼침도봉구,외식업/ 전체,75.1,50.5,31.2
12,하위 메뉴 펼침노원구,외식업/ 전체,73.7,50.7,33.8
13,하위 메뉴 펼침은평구,외식업/ 전체,74.8,48.5,30.4
14,하위 메뉴 펼침서대문구,외식업/ 전체,78.9,50.2,32.6
15,하위 메뉴 펼침마포구,외식업/ 전체,77.0,49.9,30.3
16,하위 메뉴 펼침양천구,외식업/ 전체,73.4,49.0,32.9
17,하위 메뉴 펼침강서구,외식업/ 전체,73.7,46.9,32.4
18,하위 메뉴 펼침구로구,외식업/ 전체,76.7,48.0,33.3
19,하위 메뉴 펼침금천구,외식업/ 전체,75.8,50.9,32.3
20,하위 메뉴 펼침영등포구,외식업/ 전체,78.8,52.1,36.7
21,하위 메뉴 펼침동작구,외식업/ 전체,79.8,52.2,34.2
22,하위 메뉴 펼침관악구,외식업/ 전체,71.1,49.9,29.7
23,하위 메뉴 펼침서초구,외식업/ 전체,77.0,53.7,38.4
24,하위 메뉴 펼침강남구,외식업/ 전체,74.7,50.2,33.8
25,하위 메뉴 펼침송파구,외식업/ 전체,72.3,48.1,33.2
26,하위 메뉴 펼침강동구,외식업/ 전체,71.4,48.7,32.4

In [7]:
c = b.drop(index =[0])
c.columns = ['시군구명', '서비스업종','1년생존율', '3년생존율', '5년생존율']
c = c[~(c["시군구명"].str.contains("서울시"))]

In [8]:
c["시군구명"] = c["시군구명"].str.replace(pat = "하위 메뉴 펼침",repl = "")
c["서비스업종"] = c["서비스업종"].str.replace(pat = "외식업/ ",repl = "")
c

    시군구명 서비스업종 1년생존율 3년생존율 5년생존율
2    종로구    전체  80.5  57.3  39.3
3     중구    전체  81.3  56.0  36.2
4    용산구    전체  84.6  55.7  38.3
5    성동구    전체  82.6  53.0  35.5
6    광진구    전체  76.2  52.7  32.8
7   동대문구    전체  76.4  51.5  34.3
8    중랑구    전체  74.4  45.6  30.4
9    성북구    전체  79.1  57.9  34.6
10   강북구    전체  73.4  48.2  31.7
11   도봉구    전체  75.1  50.5  31.2
12   노원구    전체  73.7  50.7  33.8
13   은평구    전체  74.8  48.5  30.4
14  서대문구    전체  78.9  50.2  32.6
15   마포구    전체  77.0  49.9  30.3
16   양천구    전체  73.4  49.0  32.9
17   강서구    전체  73.7  46.9  32.4
18   구로구    전체  76.7  48.0  33.3
19   금천구    전체  75.8  50.9  32.3
20  영등포구    전체  78.8  52.1  36.7
21   동작구    전체  79.8  52.2  34.2
22   관악구    전체  71.1  49.9  29.7
23   서초구    전체  77.0  53.7  38.4
24   강남구    전체  74.7  50.2  33.8
25   송파구    전체  72.3  48.1  33.2
26   강동구    전체  71.4  48.7  32.4

In [19]:
c["서비스업종"].unique()

array(['한식음식점', '중식음식점', '일식음식점', '양식음식점', '제과점', '패스트푸드점', '치킨전문점',
       '분식전문점', '호프-간이주점', '커피-음료'], dtype=object)

In [9]:
d = ["한식음식점", "중식음식점", "일식음식점", "양식음식점", "제과점", "패스트푸드점", "치킨전문점", "분식전문점", "호프-간이주점", "커피-음료"]
e = ["한식", "중식", "일식", "기타 외국식", "제과제빵", "패스트푸드", "치킨", "분식", "주점", "커피"]
f = dict(zip(d,e))
f

{'한식음식점': '한식',
 '중식음식점': '중식',
 '일식음식점': '일식',
 '양식음식점': '기타 외국식',
 '제과점': '제과제빵',
 '패스트푸드점': '패스트푸드',
 '치킨전문점': '치킨',
 '분식전문점': '분식',
 '호프-간이주점': '주점',
 '커피-음료': '커피'}

In [10]:
c["서비스업종"] = c["서비스업종"].replace(f)
if "분기" in c.columns:
    c.drop(columns = "분기", inplace= True)
c.insert(loc = 0, column = "분기", value = "1")
c

   분기  시군구명 서비스업종 1년생존율 3년생존율 5년생존율
2   1   종로구    전체  80.5  57.3  39.3
3   1    중구    전체  81.3  56.0  36.2
4   1   용산구    전체  84.6  55.7  38.3
5   1   성동구    전체  82.6  53.0  35.5
6   1   광진구    전체  76.2  52.7  32.8
7   1  동대문구    전체  76.4  51.5  34.3
8   1   중랑구    전체  74.4  45.6  30.4
9   1   성북구    전체  79.1  57.9  34.6
10  1   강북구    전체  73.4  48.2  31.7
11  1   도봉구    전체  75.1  50.5  31.2
12  1   노원구    전체  73.7  50.7  33.8
13  1   은평구    전체  74.8  48.5  30.4
14  1  서대문구    전체  78.9  50.2  32.6
15  1   마포구    전체  77.0  49.9  30.3
16  1   양천구    전체  73.4  49.0  32.9
17  1   강서구    전체  73.7  46.9  32.4
18  1   구로구    전체  76.7  48.0  33.3
19  1   금천구    전체  75.8  50.9  32.3
20  1  영등포구    전체  78.8  52.1  36.7
21  1   동작구    전체  79.8  52.2  34.2
22  1   관악구    전체  71.1  49.9  29.7
23  1   서초구    전체  77.0  53.7  38.4
24  1   강남구    전체  74.7  50.2  33.8
25  1   송파구    전체  72.3  48.1  33.2
26  1   강동구    전체  71.4  48.7  32.4

In [11]:
c.to_csv("./신생기업생존율전체.csv", encoding="ansi", index = False)